baseURL = "https://blog.fagner.co"
theme = "binario"
title = "Fagner's Blog"

[Params.Author] # Used in authorbox
  name = "Fagner Nunes Carvalho"
  bio = "Developer for over 10 years now, I have seen a little bit of everything."
# avatar = "img/avatar.png"

[Params]
  description = "Fagner Nunes Carvalho personal blog" # Site Description. Used in meta description
  copyright = "Fagner Nunes Carvalho" # Copyright holder, otherwise will use .Site.Title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  columns = 1 # Set the number of cards columns. Possible values: 1, 2, 3
  mainSections = ["post"] # Set main page sections
  dateFormat = "January 02, 2006" # Change the format of dates
  colorTheme = "dark-blue" # dark-green, dark-blue, dark-red, dark-violet
# customCSS = ["css/custom.css"] # Include custom CSS files
# customJS = ["js/custom.js"] # Include custom JS files
  mainMenuAlignment = "right" # Align main menu (desktop version) to the right side
  authorbox = true # Show authorbox at bottom of single pages if true
  comments = true # Enable comments for all site pages
  related = true # Enable Related content for single pages
  relatedMax = 5 # Set the maximum number of elements that can be displayed in related block. Optional
  mathjax = true # Enable MathJax for all site pages
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path. Optional
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config. Optional
  hideNoPostsWarning = false # Don't show no posts empty state warning in main page, if true

[Params.Entry]
  meta = ["date", "categories", "tags"] # Enable meta fields in given order
  toc = false # Enable Table of Contents
  tocOpen = true # Open Table of Contents block. Optional

[Params.Featured]
  previewOnly = false # Show only preview featured image

[Params.Breadcrumb]
  enable = true # Enable breadcrumb block globally
  homeText = "Fagner's Blog" # Home node text

[Params.Social]
  linkedin = "fagnerncarvalho"
  github = "fagnercarvalho"
  stackoverflow = "1459499"

[Params.Share] # Entry Share block
  twitter = true
  reddit = true
  linkedin = true
  stackoverflow = true

[outputs]
  home = ["HTML", "RSS"]